import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import OtpModal from "@/components/OtpModal";
import { cn } from "@/lib/utils";

import { AuthProvider } from "@/context/AuthContext"; 

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        
        {/* 2. WRAP CHILDREN IN THE AUTH PROVIDER */}
        <AuthProvider>
          {children}
          <OtpModal />
        </AuthProvider>
        
      </body>
    </html>
  );
}